---
openapi: 3.0.3
info:
  title: Github challenge swagger
  description: |-
    Project built to complete a github challenge
  contact:
    name: Victor Hugo
    email: victor.hugo.ufpb@gmail.com
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:9092
    description: dev
tags:
  - name: Github
    description: Everything about the github repository
paths:
  /users/{username}/repos:
    get:
      tags:
        - Github
      summary: Get repository info
      description: Get information about the repository and branches from a username
      operationId: getRepositoryInfo
      parameters:
        - name: username
          in: path
          description: user login
          required: true
          schema:
            type: string
            example: victorufpb
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RepositoryInfo'
        '404':
          description: Repository not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '412':
          description: Pre condition failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - BasicAuth: [ ]
components:
  schemas:
    RepositoryInfo:
      type: array
      items:
        $ref: '#/components/schemas/UserRepositoryInfo'
    ErrorResponse:
      required:
        - status
        - Message
      type: object
      properties:
        status:
          type: integer
          format: int32
          example: 123
        Message:
          type: string
          example: Error message
    BranchInfo:
      type: object
      properties:
        name:
          type: string
          example: myBranchName
        commit_sha:
          type: string
          example: c827e59b53054bffcfe10faee915a0aaebacf6e9
    UserRepositoryInfo:
      type: object
      properties:
        repository_name:
          type: string
          example: my_repository
        owner_login:
          type: string
          example: victorufpb
        branches_info:
          type: array
          description: list of branches and its last commit sha
          items:
            $ref: '#/components/schemas/BranchInfo'
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic